# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: primary_left_leg
  joint_model_group_pose: primary_left_leg_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - pl_pectoral
    - pl_humerus
    - pl_radius
    - pl_carpal
    - pl_foot
    - pl_pectoral_Tertiary
    - pl_humerus_Tertiary
    - pl_radius_Tertiary
    - pl_carpal_Tertiary
    - pl_foot_Tertiary
    - pl_pectoral_right
    - pl_humerus_right
    - pl_radius_right
    - pl_carpal_right
    - pl_foot_right
    - pl_pectoral_right_Tertiary
    - pl_humerus_right_Tertiary
    - pl_radius_right_Tertiary
    - pl_carpal_right_Tertiary
    - pl_foot_right_Tertiary
    - pl_pectoral_right_secondary
    - pl_humerus_right_secondary
    - pl_radius_right_secondary
    - pl_carpal_right_secondary
    - pl_foot_right_secondary
    - pl_pectoral_secondary
    - pl_humerus_secondary
    - pl_radius_secondary
    - pl_carpal_secondary
    - pl_foot_secondary
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []